Feature/followrelation
lupa-project/lupa-api pull request #9
Opened 2019-09-02 03:57 UTC by KANCHOEUN

Create FollowRelation Model

2019-09-02 14:51 UTC, strutive07 requested changes
전체적으로 follow 에 대한 flow chart 를 그려보시고, 어느 부분에서 get, 어느 부분에서 update 어느 부분에서 delete 가 이루어질지 flow chart 를 그려서 업로드 해주시면 좋을거같습니다.

2019-09-02 14:51 UTC, strutive07 commented on board/models/card.py
> +        verbose_name_plural = '{} {}'.format(verbose_name, '목록')
__str__ 에서는 f string을 사용하였으니 이 부분에서도 format string 말고 f string을 사용해주세요.

2019-09-02 14:51 UTC, strutive07 commented on user/models/follow_relation.py
> +        follow_info.save()
이미 get_or_create 를 해두었으니, save 를 한번 더할 필요는 없습니다.

2019-09-02 14:51 UTC, strutive07 commented on user/models/follow_relation.py
> +            return not created
지금 전체적으로 함수들에 docstring  이 없는데, docstring 을 달아주세요. type은 google 로 해주시면됩니다.

2019-09-02 14:51 UTC, strutive07 commented on user/models/follow_relation.py
> +        follow_info, created = FollowRelation.objects.get_or_create(
A -> B follow 이 이미 되어있는 상태에서 한번 더 follow 요청이 비정상적으로 올 경우, 방어로직이 없습니다.
이 로직대로라면 approve 가 2번 불린다면 get_or_create 를 통해 비정상적인 데이터가 생성될것입니다.
approve 는 get 으로만 처리해주시고, DoseNotExist 예외처리를 해주시면 될거같습니다.

2019-09-02 14:51 UTC, strutive07 commented on user/models/follow_relation.py
> +        follow_info, created = FollowRelation.objects.get_or_create(
밑에 리뷰를 달아두었었는데, unfollow 라면, 이미 follow 가 있어야 하는 상태인데 get_or_create 이면 비정상적인 데이터가 생성될거같습니다. get 으로 해주세요.

2019-09-02 14:51 UTC, strutive07 commented on user/models/follow_relation.py
> +        follow_info.save()
또한, return 으로 follow_info 를 return 하는것이 더 좋지 않을까요?.

2019-09-02 14:51 UTC, strutive07 commented on user/models/follow_relation.py
> +        follow_info, created = FollowRelation.objects.get_or_create(
이부분도 get 으로 해주세요.
로직상 follow 는 1번만 있어야하며, 1번 생성되는 부분은 follow 에서만 있어야합니다.

2019-09-02 14:51 UTC, strutive07 commented on user/models/follow_relation.py
> +    CHOICES_TYPE = (
Choice field 는 from model_utils import Choices 를 사용해주세요 (만약 requirments 에 없다면 추가해주세요.)

2019-09-18 11:36 UTC, strutive07 approved these changes
고생하셨습니다. 굳!

2019-09-18 11:41 UTC, n0rr7882 reviewed
고생하셨습니다!

2019-09-18 11:41 UTC, n0rr7882 commented on user/models/follow_relation.py
> +            to_user (An instance of UserFollowInfo):
타입힌팅을 위해서 `to_user(UserFollowInfo)` 로 기입해주셔야 합니다

2019-09-18 11:41 UTC, n0rr7882 commented on user/models/follow_relation.py
> +            An instance of FollowRelation or None
여기도 `FollowRelation:` 만으로 충분합니다

2019-09-18 11:50 UTC, merged